- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  setPreference: true # DeltaV - Readded Senior roles (removed upstream)
  requirements:
    - !type:RoleTimeRequirement
      role: JobChemist
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 43200 #12 hrs
    - !type:RoleTimeRequirement
      role: JobParamedic
      time: 21600 #6 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 108000 # 30 hrs
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  - Paramedic

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    innerClothingSkirt: ClothingUniformJumpskirtSeniorPhysician
    satchel: ClothingBackpackSatchelMedicalFilled
    duffelbag: ClothingBackpackDuffelMedicalFilled
