- type: job
  id: SeniorResearcher
  name: job-name-senior-researcher
  description: job-description-senior-researcher
  playTimeTracker: JobSeniorResearcher
  setPreference: true # DeltaV - Readded Senior roles (removed upstream)
  requirements:
    - !type:DepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      time: 216000 #60 hrs
  startingGear: SeniorResearcherGear
  icon: "JobIconSeniorResearcher"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: SeniorResearcherGear
  equipment:
    id: SeniorResearcherPDA
    ears: ClothingHeadsetScience
    innerClothingSkirt: ClothingUniformJumpskirtSeniorResearcher
    satchel: ClothingBackpackSatchelScienceFilled
    duffelbag: ClothingBackpackDuffelScienceFilled
