- type: antag
  id: Dragon
  name: roles-antag-dragon-name
  antagonist: true
  objective: roles-antag-dragon-objective
  requirements:
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Antag roles
