- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobMedicalBorg

#- type: playTimeTracker # Echo: No justice
#  id: JobChiefJustice
#
#- type: playTimeTracker # Echo: No justice
#  id: JobClerk

- type: playTimeTracker
  id: JobProsecutor

- type: playTimeTracker
  id: JobCourier

- type: playTimeTracker
  id: JobSecurityBorg
